### PR TITLE
ember-fetch 8.1.2

### PR DESCRIPTION
**Pull request by Dhaulagiri**
removes deprecated Ember global reference

### CODE REVIEW

**Comment by elwayman02** [comment]
@Dhaulagiri I know this has been sitting for a while, but I just merged a big set of updates to clean things up. If you can rebase your branch, this should be a simple merge as a follow-up.

**Comment by elwayman02** [comment]
Oh no, one of the dependabot PRs I was merging created a new conflict. Sorry! One more rebase should do it, I'll hold off on merging anything else until we get this one in.

**Comment by Dhaulagiri** [comment]
@elwayman02 no problem. should be good now

**Comment by elwayman02** [comment]
Thank you for rebasing this and getting the fix in!

**Pull request merged**
